spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12315
    url: jdbc:mysql://localhost:3306/plane?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true

  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
#  jackson:
#    date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql


